enum Errors {
    OnlyOwner = 1009
    OnlyWallet = 1010
    OrderLimitReached = 1011
    OrderAlreadyExists = 1012
    OrderNotFound = 1013
    OrderExpired = 1014
    InvalidSessionKey = 1015
    SessionKeyExpired = 1016
    InvalidSeqno = 1017
    TriggerKeyNotSet = 1018
    WrongExtensionInstance = 1019
    InvalidSignature = 1020
    Expired = 1021
    UnsafeSendMode = 1022
    WrongOrderNonce = 1023
    UnsupportedExternalMessage = 0xFFFF
}
